# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1fb1423cb79583ddbd8395c1351721d974ed492485794f4364d79e7626e7383a763bcf4a812dc76590825a88320713098ee2ce1f1e9ea7a44ab05372b4bd6aa

test:
  secret_key_base: 22c2dbb30fec16ebfde75d7f712538a955131f36c0adc123915ec255af53dbe96be6bcf3d4e1fbc324415c39596fd57a244f31352de5ec8eccffb945cf383820

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
